### ISSUE TITLE
lfetool Version 2.0 Development Plan (Epic)

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#46]
## Epic: Version 2 Project Tracking

This ticket gives an overview of the work to be done in Version 2 of `lfetool`.  Though this ticket represents the `develop` branch in the repo, actual coding will not happen against this ticket. Rather, new ones will be opened with their branches merged to `develop` when complete.

Once all features have landed, been merged to `develop`, and `lfetool` behaves as expected, having been fully tested, we will merge `develop` to `master`.
## Overview of Dev Plan

In a conversation on IRC, I managed to talk myself (pretty easily/quickly, tbh) into a Version 2 implementation of `lfetool`. It will follow more closely the `lein` tool which inspired it in the first place:
- there will be a shell script named `lfetool` which will
  - bootstrap itself when first run
  - provide a compatibility layer for different shells and OSes
- most of the functionality of `lfetool` will be moved into LFE library files
- there will be an entry-point (probably written in LFE) which will dispatch to lfetool plugins (library files)
- the entry-point will be called from the `lfetool` shell script (probably using @rvirding's new `lfe` script + parameter handling)
## Outstanding Questions
- What about bootstrapping for other things? For instance, installing things like Erlang (via `kerl`) or  `rebar`?
  - Robert has a potential answer for this: include lfetool with lfe and use lfetool for everything by default (downloading, compiling, dependency configs, etc.).
## Resources
- Inspiration will be taken from `lein`: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
- Work on this will be done in the `develop` branch: https://github.com/lfe/lfetool/tree/develop
- Full dev plan notes (including the IRC conversation which inspired this work) are kept here: https://github.com/lfe/lfetool/blob/develop/doc/notes/version2-dev-plan.md
## Sub-Tickets

Sub-tickets (stories) for this epic are listed below in the comments (to take advantage of active checkboxes in Github markdown).

**Comment by oubiwann** [comment]
### Version 2.0
- [x] [Figure out new architecture](https://github.com/lfe/lfetool/issues/47)
- [x] [Figure out plugin development workflow](https://github.com/lfe/lfetool/issues/48)
- [x] [Define and use plugin behaviour](https://github.com/lfe/lfetool/issues/55)
- [x] [Implement a command parser](https://github.com/lfe/lfetool/issues/59)
- [ ] [Figure out bootstrapping](https://github.com/lfe/lfetool/issues/49)
- [ ] [Figure out plugin system internals](https://github.com/lfe/lfetool/issues/50)
- [x] [Implement command dispatching](https://github.com/lfe/lfetool/issues/60) (uses the results from the parser)
- [ ] [Document plugin development process](https://github.com/lfe/lfetool/issues/70)
- [ ] [Abstract shell coloring to utility library](https://github.com/lfe/lfetool/issues/61) (maybe its own little project?)
- [ ] [Dynamically generate Bash auto-complete file](https://github.com/lfe/lfetool/issues/69)
- [ ] [Migrate plugins](https://github.com/lfe/lfetool/issues/81)

### Version 2.1

The following have been moved into the next release:
- [ ] [Add a download wrapper](https://github.com/lfe/lfetool/issues/51)
- [ ] [Provide a means of managing customized dependencies](https://github.com/lfe/lfetool/issues/52)
- [ ] [Add a compile command](https://github.com/lfe/lfetool/issues/53)
