### ISSUE TITLE
Command Migration Plan (Epic)

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#81]
The following commands need to be migrated
- [x] `info *` (see https://github.com/lfe/lfetool/issues/78)
  - [x] `info bindir` command
  - [x] `info erllibs` command
  - [x] `info installdir` command
  - [x] `info path` command
  - [x] `info version` command
- [ ] `install *`
  - [ ] `install autocomplete` command
  - [ ] `install erjang` command
  - [ ] `install expm` command
  - [ ] `install lfe` command
  - [ ] `install lfetool` command
  - [ ] `install rebar` command
  - [ ] `install relx` command
  - skip `install kerl` and `install erlang` -- those will be done by the bootstrapping shell script
- [ ] `update *`
  - [ ] `update deps` command
  - [ ] `update lfetool` command
- [x] `repl *`
  - [x] - `repl` command
  - [x] - `repl lfe` command
  - [x] - `repl erl` command
  - [x] - `repl erlang` command (alias)
  - [x] - `repl jlfe` command
  - [x] - `repl erjang` command (alias)
  - [x] - `repl jerl` command
- [x] `new *`
  - [x] https://github.com/lfe/lfetool/issues/58 - `new script` plugin
  - [x] https://github.com/lfe/lfetool/issues/62 - `new lfetool` plugin - skipped/NA
  - [ ] https://github.com/lfe/lfetool/issues/63 - `common` meta-plugin
  - [ ] https://github.com/lfe/lfetool/issues/64 - `new library` plugin
  - [ ] https://github.com/lfe/lfetool/issues/65 - `new service` plugin
  - [ ] https://github.com/lfe/lfetool/issues/66 - `new yaws` plugin
  - [ ] https://github.com/lfe/lfetool/issues/67 - `new yaws bootstrap` plugin
  - [ ] https://github.com/lfe/lfetool/issues/68 - `new yaws presentation` plugin
- [ ] `tests *` (see issue #83)
  - [ ] - `tests all` command
  - [ ] - `tests build` command
  - [ ] - `tests integration` command
  - [ ] - `tests system` command
  - [ ] - `tests unit` command

**Comment by oubiwann** [comment]
It was easier to just do the REPL support in the shell script: 36b997b.
