### ISSUE TITLE
New Command Plan (Epic)

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#82]
The following commands do not exist in lfetool v1 and we'd like to add them for v2:
- [ ] `info *` (see issue #78)
  - [x] - `info plugins` command
  - [ ] - `info versions` command - this would display all version info (currently done by `info version`) and then let `version` only display the one version number for lfetool itself
- [ ] `build *` (see issue #22)
  - [ ] - `build` command (alias for `build all`)
  - [ ] - `build all` command
  - [ ] - `build deps` command
  - [ ] - `build plugins` command
  - [ ] - `build src` command
  - [ ] - `build tests` command (alias)
  - [ ] - `build bashcomplete` command (this will depend upon issue #69)
- [ ] `download *` (see issue #51)
  - [ ] - `download`
  - [ ] - `download git <repo>` command
  - [ ] - `download curl <url>` command
  - [ ] - `download wget <url>` command
- [ ] `new *`
  - [ ] - `new plugin <type> <name>` command (or maybe just `new plugin <name>`? See issue #72 )
  - [ ] - `new e2-service <name>` command
- [ ] `publish *`
  - [ ] - `publish` - alias for `expm publish`
  - [ ] - `publish expm` - alias for `expm publish`
  - [ ] - `publish git` - alias for `git push origin master && git tag <current-version>`
  - [ ] - `publish git` - alias for `git push origin master && git tag <current-version>`
  - [ ] - `publish git <repo> <branch>` - alias for `git push <repo> <branch> && git tag <current-version>` 
- [ ] `remove *`
  - [ ] - `remove beams` command (alias for `beams all`)
  - [ ] - `remove beams all` command
  - [ ] - `remove beams project` command
  - [ ] - `remove beams plugin` command
  - [ ] - `remove beams test` command
- [ ] `tests *`
  - [ ] - `tests <test-module>`
  - [ ] - `tests <test-module>:<test-function>`
  - [ ] - `tests <path-to-test-file>.lfe`
  - [ ] - `tests <path-to-test-file>.lfe <test-function>`
- [ ] `update *`
  - [ ] - `update kerl` command
  - [ ] - `update erjang` command (see issue #19)

Some of these might need to be broken out into their own tickets.
